### PR TITLE
Move require blocks outside the constructor

### PR DESCRIPTION
**Pull request by jd-carroll**

### CODE REVIEW

**Comment by dmvaldman** [comment]
I recall the reason for putting it in the constructor was because there is a circular reference: Stream requires MergedStream, and MergedStream requires stream. If the require statement is hoisted to the top, it doesn't work. 

The reason for the circular reference was just to hide MergedStream from the API surface area. It's in the background when you call Stream.merge or Stream.lift. Maybe there's another way to avoid the circular reference? As it stands I don't think this PR works though (Stream in MergedStream won't resolve)

**Comment by jd-carroll** [comment]
Once again you are absolutely correct, and I found it interesting the way
you are using `Stream` in `DrawerLayout`, `Accumulator`, and `Differential`
(particularly `DrawerLayout`).  You're essentially creating a
`MergedStream` that batches events without providing a stream map.

Not that it is at all necessary, but it may be possible to refactor the
`Stream` constructor into a separate "`BatchStream`" or something like that
to break the cycle.  (Again, I don't think that is at all required)

**Comment by dmvaldman** [comment]
That's right. `Stream.map` is good for when you want to create a new stream that depends on a single quantity. `Streap.lift` is the generalization where you want to create a new stream that depends on multiple quantities.

These are essentially equivalent:

```
var newStream = oldStream.map(function(value){...});
```

```
var newStream = Stream.lift(function(value){...}, [oldStream])
```

But in general the `Stream.lift` can handle multiple dependencies.

```
var newStream = Stream.lift(function(value1, value2, ...){...}, [oldStream1, oldStream2,...])
```

**Comment by dmvaldman** [comment]
Your Batch stream refactor is also a good one. It was actually on my todo list! I also don't like the current naming of things like 'simplestream'. This part of the codebase is still a little immature.

**Pull request closed without merging**
