### PR TITLE
Added ReactSurface - a surface that renders React components

### PR DESCRIPTION
**Pull request by TDSFugal**
Hi Dave,

I wrote a candidate for your Samsara collection.  It's a Surface that renders React components.  I've tested it in my Meteor build system and it seems to work just fine, but I don't know how to test it in yours.  It requires both React and ReactDOM to function.

I've given a lot of thought to how to architect a 3D application that contains business logic and agree with your insight wrt separation of concerns.  For me the most logical approach is to have 3 major logic structures - the business logic graph (or tree if you use a Redux/Flux dispatcher approach), the non-business logic shape/size/position render tree (a la Samsara), and the DOM which is ideally very flat to minimize couplings.  The business logic graph and render tree intersect at the leaves of the tree with a Surface holding a small React render structure presenting data and accepting user input with no concept of where it is or how/why it got there.  I built this class to implement and test this architecture. 

I can't claim it is bug free, but it does seem like a good start.  I can see I need to add a few more comments...  The only new method is the "renderWithProps" method.  This updates the _component every time new props are provided.  React.render does not actually re-render the _component class every time it is called.  On the first call React.render evaluates the code provided by createElement; after that, it just verifies that the _component parameter is the same and only operates on the changes in the props parameter.

Best,

Tim Smith

### CODE REVIEW

**Comment by dmvaldman** [comment]
Hi @TDSFugal, this is similar to the approach I had in mind. I think where it gets complicated is during DOM mutation. For instance, when the react component is removed, the surface will also need to be removed. In the latest samsara release there is now a `remove` method on `surface` and `view`. Adding the surface back in will make it reappear and contain its previous state. Something like this will need to work well with React and other libraries.

I'd also like to see this not as a part of Samsara, but in a small samsara-react library. If a user wants to use both libraries, she would include both libraries and the shim layer. Then she would somehow associate a samsara `surface` or `view` with a React component. Something like `samsara-react.bind(samsaraSurface, reactComponent)`. This way it's not that React is a parent of Samsara, or Samsara a parent of React, but they exist on the same level.

**Comment by TDSFugal** [comment]
Works for me.  Will see what I can do.

**Comment by aprender** [comment]
Hi Gents,

This is particularly cool, however I am curious about the render loop
causing a full React update 60 times per second and the possibility that it
will add significant overhead checking the state for changes that
frequently.

Have you noticed any performance problems so far with your implementation
or have you manged to avoid firing off React's DOM tree updating algorithm
inside the Samsara render loop?

ap

**Comment by dmvaldman** [comment]
There's data that changes at 60fps, and there's data that changes every once in a while. Having React's render loop control the latter and Samsara's render loop control the former is key.

**Comment by aprender** [comment]
Totally agree. If you have nailed getting that separation of concerns right
then this is huge.

ap

**Pull request closed without merging**
